# Generated by Django 6.1.1 on 2026-09-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('INCIDENT_SUBMITTED', 'Incident Submitted'), ('INCIDENT_VERIFIED', 'Incident Verified'), ('INCIDENT_REJECTED', 'Incident Rejected'), ('INCIDENT_ASSIGNED', 'Incident Assigned'), ('INCIDENT_STATUS_CHANGED', 'Incident Status Changed'), ('INCIDENT_RESOLVED', 'Incident Resolved'), ('INCIDENT_CLOSED', 'Incident Closed')], max_length=40),
        ),
    ]
